### ISSUE TITLE
FileNotFoundError: log/transformer_PROTAC_random_protac7000_zinc300000.txt

### ISSUE THREAD

**Issue by dbhaskar92** [biomed-AI/PROTAC-RL#1]
Here are the steps to reproduce this error:

1) `bash preprocess.sh` with `dataset_name=ZINC` and `random=canonical`
2) `bash preprocess.sh` with `dataset_name=PROTAC` and `random=random`
3) `cp data/ZINC/canonical/.vocab.pt data/PROTAC/random/`
4) `bash fine-tune-training.sh`

I made a small change to `fine-tune-training.sh`, I replaced the mkdir command with `mkdir -p $pathsave`.

Here is the error in full:

```
Traceback (most recent call last):
  File "train.py", line 118, in <module>
    main(opt)
  File "train.py", line 51, in main
    single_main(opt, 0)
  File "/gpfs/gibbs/pi/krishnaswamy_smita/dbhaskar/projects/PROTAC-RL/onmt/train_single.py", line 87, in main
    init_logger(opt.log_file)
  File "/gpfs/gibbs/pi/krishnaswamy_smita/dbhaskar/projects/PROTAC-RL/onmt/utils/logging.py", line 19, in init_logger
    file_handler = logging.FileHandler(log_file)
  File "/home/db2454/gibbs/dbhaskar/conda_envs/PROTAC-RL/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/db2454/gibbs/dbhaskar/conda_envs/PROTAC-RL/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/gpfs/gibbs/dbhaskar/projects/PROTAC-RL/log/transformer_PROTAC_random_protac7000_zinc300000.txt'
```

**Comment by TanYoh** [comment]
Hello Dhananjay Bhaskar:
1. It's our mistake to forget pre-training step in the example of README. Please follow new example process to train PROTAC-RL.
2. It seems that github ignored origin empty **log folder** in our code. Therefore your program couldn't find `log/transformer_PROTAC_random_protac7000_zinc300000.txt`. You can `mkdir` a new **log folder** to solve this problem.
