### ISSUE TITLE
No such file or directory: '/PROTAC-RL/log/transformer_ZINC_random_1.txt'

### ISSUE THREAD

**Issue by franksyng** [biomed-AI/PROTAC-RL#2]
Hi I was just trying to run a demo of this project, however an error occurred when I ran the file training.sh.

training.sh: line 7: [: missing `]'
mkdir: cannot create directory ‘checkpoints/ZINC/random’: File exists
Traceback (most recent call last):
  File "/content/PROTAC-RL/train.py", line 118, in <module>
    main(opt)
  File "/content/PROTAC-RL/train.py", line 51, in main
    single_main(opt, 0)
  File "/content/PROTAC-RL/onmt/train_single.py", line 87, in main
    init_logger(opt.log_file)
  File "/content/PROTAC-RL/onmt/utils/logging.py", line 19, in init_logger
    file_handler = logging.FileHandler(log_file)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
FileNotFoundError: [Errno 2] No such file or directory: '/content/PROTAC-RL/log/transformer_ZINC_random_1.txt'

Could you please help me figure out the problem? thx

**Comment by TanYoh** [comment]
Hi, Frank Ng
You could find solution in this closed issue:
