### ISSUE TITLE
Data Missing?

### ISSUE THREAD

**Issue by LongchaoDa** [biomed-AI/PROTAC-RL#5]
Hi Thanks for the great work, I am learning a lot from the paper. When I try to implement the code, I faced the below problem, it is obvious that `.train.py` is missing, under the folder of `data/ZINC/` I could only find `canonical` under the repo folder `data/ZINC/`, am I missing something, or how could I fix this issue? Thanks!

> Traceback (most recent call last):
  File "train.py", line 124, in <module>
    main(opt)
  File "train.py", line 35, in main
    single_main(opt, -1)
  File "PROTAC-RL/onmt/train_single.py", line 100, in main
    first_dataset = next(lazily_load_dataset("train", opt))
  File "PROTAC-RL/onmt/inputters/inputter.py", line 553, in lazily_load_dataset
    yield _lazy_dataset_loader(pt, corpus_type)
  File "PROTAC-RL/onmt/inputters/inputter.py", line 539, in _lazy_dataset_loader
    dataset = torch.load(pt_file)
FileNotFoundError: [Errno 2] No such file or directory: 'data/ZINC/random/.train.pt'

**Comment by LongchaoDa** [comment]
Btw, this happened after I execute the command `bash training.sh`

**Comment by LongchaoDa** [comment]
Thanks I figured out myself!
